services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
    volumes:
      - .:/var/www
      - /var/www/node_modules
    command: npm run dev